### ISSUE TITLE
Not compatible with ip-win32 ipapi

### ISSUE THREAD

**Issue by shaynem** [ValdikSS/openvpn-fix-dns-leak-plugin#10]
First of all - much required contribution to openvpn and thank you for creating this plugin

When having the option ip-win32 ipapi in the openvpn config, this plugin fails to work 

Same happens when using openvpn 2.3.10 with the --block-outside-dns

Sometimes when connection problems arise in windows, using ip-win32 netsh (works ok with the plugin/--block-outside-dns) or ip-win32 ipapi is required to be set to get a stable connection

There is no errors in the log, however no IP connectivity either when using this plugin or --block-outside-dns switch in later versions of openvpn

**Comment by ValdikSS** [comment]
Hi!
`--ip-win32 ipapi` doesn't support `--dhcp-option`'s, so it can't set DHCP server:

```
−−dhcp−option type [parm]

Set extended TAP-Win32 TCP/IP properties, must be used with
−−ip−win32 dynamic or −−ip−win32 adaptive. This option can be used
to set additional TCP/IP properties on the TAP-Win32 adapter, and is
particularly useful for configuring an OpenVPN client to access a Samba
server across the VPN.
```
