### ISSUE TITLE
OpenVPN Error when loading plugin

### ISSUE THREAD

**Issue by msimechak** [ValdikSS/openvpn-fix-dns-leak-plugin#11]
Every time OpenVPN goes to load the plugin, I get the following error:

![2016-02-26_14-25-17](https://cloud.githubusercontent.com/assets/16603826/13364531/e9213814-dc94-11e5-9ed5-7d979e351518.png)

I am using the 64 bit DLL, with a 64 bit version of OpenVPN, on a Windows 10 64 system, just for the record.  Not sure why it won't load.  Other people don't seem to have this problem.

**Comment by msimechak** [comment]
Never mind.  It still doesn't work for me, but I got the "block-outside-dns" argument working.  I was trying to use it as an argument on the openvpn-GUI.exe instead of just using it as an argument in my .ovpn file so that openvpn.exe is what calls it.  Duh. 

Works just fine, and I can see it in the log file:

Fri Feb 26 14:49:01 2016 Blocking outside DNS

**Comment by ValdikSS** [comment]
> Not sure why it won't load.

Because you've downloaded HTML page, not dll file.

**Comment by msimechak** [comment]
Haha, that's exactly what my dumb self was doing.  Thanks.  I always forget to download the project ZIP instead of trying to download each individual file.  Works perfectly when I download the DLL instead of saving an HTML file.

Thanks!

**Comment by ValdikSS** [comment]
Anyway, please use `block-outside-dns` OpenVPN option. With newer OpenVPN versions this plugin is obsolete. The only thing that there's a bug in OpenVPN 2.3.10 `block-outside-dns` which prevents it from working on Windows Vista, it would be fixed in OpenVPN 2.3.11. The plugin works on Vista though.
