### ISSUE TITLE
--block-outside-dns on Raspberry!!!!

### ISSUE THREAD

**Issue by ducarpit** [ValdikSS/openvpn-fix-dns-leak-plugin#12]
Hi,
i have OpenVPN on my Raspberry.
Unofrtunatly i have the `OpenVPN 2.3.4 arm-unknown-linux-gnueabihf` version. and this works only in the 2.3.9.
Where i can insert the --block-outside-dns? In the server config file? Will i use also the fix-dns-leak-64.dll on my client?
Thank a lot

**Comment by ValdikSS** [comment]
You can't. This functionality works only on Windows. OpenVPN can handle DNS only on Windows. On other platforms (Linux, macOS) you need to use up/down scripts to handle DNS changes. Usually these scripts come with your distro. On Ubuntu these scripts are in `/etc/openvpn`.

**Comment by ducarpit** [comment]
Hy my dear friend, thanks a lot...
I have two client: the first one with Windows 10 so i think i have to add the line "block-outside-dns" to the client ovpn file and the line "plugin fix-dns-leak-64.dll" that point to the script in C:/Program Files/OpenVPN/bin, am i right?
The second client is an Ubuntu 16.04: in the /etc/openvpn directory i have only a file called update-resold-conf: is it? How can i use this?
Finally the question is: the server is a Raspberry Pi3 with OpenVPN 2.3.4, can i use this function with this version? Because the article says that OpenVPN 2.3.9 are required.
Thanks a lot

**Comment by ValdikSS** [comment]
For Windows 10 you only need to either add `block-outside-dns` to the client config or push this option from server. This would work with OpenVPN 2.3.9 on the client side, and newer. It doesn't matter what server version you have.

For Ubuntu you need to add the following lines to the client config file:
```
up /etc/openvpn/update-resolv-conf
down /etc/openvpn/update-resolv-conf
```

**Comment by ducarpit** [comment]
Hi, i tried this in Windows 10 adding _block-outside-dns_ in my client config file.
When i connect to the VPN, OpenVPN say this: 
```
Tue Jul 18 09:59:58 2017 Block_DNS: WFP engine opened
Tue Jul 18 09:59:58 2017 Block_DNS: Using existing sublayer
Tue Jul 18 09:59:58 2017 Block_DNS: Added permit filters for exe_path
Tue Jul 18 09:59:58 2017 Block_DNS: Added block filters for all interfaces
Tue Jul 18 09:59:58 2017 Block_DNS: Added permit filters for TAP interface
```
So i think it's all ok.....
But unfortunatly, in a domain network this doesn't work because i can't access some website such ad google.com, ilmeteo.it or google.news.com....i can access only blocked web sites like facebook.com, instagram.com ecc

**Comment by ValdikSS** [comment]
You need to push DNS configuration from server, and to push route to it.
Please read the manual.

**Comment by ducarpit** [comment]
I have already do it: 
```
server 10.8.0.0 255.255.255.0
# server and remote endpoints
ifconfig 10.8.0.1 10.8.0.2
# Add route to Client routing table for the OpenVPN Server
push "route 10.8.0.1 255.255.255.255"
# Add route to Client routing table for the OPenVPN Subnet
push "route 10.8.0.0 255.255.255.0"
# your local subnet
push "route 192.168.1.0 255.255.255.0"
# Set your primary domain name server address for clients
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
# Override the Client default gateway by using 0.0.0.0/1 and
# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
```

**Comment by ValdikSS** [comment]
Use wireshark/tcpdump to determine the reason it doesn't work for you. I can't help you remotely. Go to OpenVPN forums or IRC channel.

**Comment by ducarpit** [comment]
I installed tcpdump (on Windows) and i tryed to examine the output...unfortunatly i'm not very able, it seems all ok but it's not right.....Where can i receive an help/assistance?

**Comment by ValdikSS** [comment]
Try to seek help on IRC #openvpn@irc.freenode.net

**Comment by ducarpit** [comment]
Perfect....so i can send an email to openvpn@irc.freenode.net, am i right?

**Comment by ValdikSS** [comment]
No, that's an IRC channel, not a email address.

**Comment by mmjo** [comment]
> For Windows 10 you only need to either add `block-outside-dns` to the client config or push this option from server. This would work with OpenVPN 2.3.9 on the client side, and newer. It doesn't matter what server version you have.
> 
> For Ubuntu you need to add the following lines to the client config file:
> 
> ```
> up /etc/openvpn/update-resolv-conf
> down /etc/openvpn/update-resolv-conf
> ```

For the scripts to run you also need to add:
script-security 2
