### ISSUE TITLE
Where do I put this ;-;

### ISSUE THREAD

**Issue by rectof** [ValdikSS/openvpn-fix-dns-leak-plugin#13]
Do I put this in the server conf or the client conf?

This is what my client conf looks like btw, --block-outside-dns broke it :/

dev tun
proto udp
remote 74.91.123.222 1194
;http-proxy-retry
;http-proxy [proxy server] [proxy port]
cipher AES-128-CBC
auth SHA1
resolv-retry infinite
nobind
persist-key
persist-tun
client
verb 3
auth-user-pass
--block-outside-dns

**Comment by ValdikSS** [comment]
You either put it into client config or push from server. Go read the manual.
