### ISSUE TITLE
It seems not works

### ISSUE THREAD

**Issue by byman64** [ValdikSS/openvpn-fix-dns-leak-plugin#6]
GOAL:  I would like use only the OpenVPN dns released after the vpn connection.

I have the host mail.xxx.com with a public IP but when I am in vpn I would like use the private IP as descripted in the openvpn dns

As read on internet windows 8/10 make a parallel request and get the faster reply.

So I find your dll plugin

I downloaded the fix-dns-leak-64.dll and I store it on C:\Program Files\OpenVPN\bin

It's that the correct path?

then I wrote an new entry in my config file.ovpn :
 plugin fix-dns-leak-64.dll

thanks in advance

**Comment by ValdikSS** [comment]
Yes, you did everything right. How exactly doesn't it work? Does it leaks DNS or just won't connect?

**Comment by byman64** [comment]
OpenVPN connection woks fine but Windows 10 is still using the Lan DNS and not the openVPN dns.

"Ethernet 3" is the LAN interface with dns 8.8.8.8
"Ethernet" is the openVPN interface with dns 10.6.22.1 (it can solve private and public ip)

Ping to mail.xxx.com still release the public ip because he is using 8.8.8.8

if I force the dns for lan interface with something like 
- netsh interface IPv4 set dnsserver "Ethernet 3" static 10.6.22.1 both
- ipconfig /flushdns

Ping will return the private IP

after openVPN disconnect, the following commands will restore the dns 
- netsh interface IPv4 set dnsserver "Ethernet 3" dhcp
- ipconfig /flushdns

So I dont know why your plugin does not work...

what I can try?

**Comment by ValdikSS** [comment]
Try older version which doesn't block only svchost but all software:
https://github.com/ValdikSS/openvpn-fix-dns-leak-plugin/blob/a968d14ef92a2db5500e8f4dbd978f3dd06649db/fix-dns-leak-64.dll

**Comment by byman64** [comment]
ops, now I get an error on DLL, I didnt change anything...just reconnect.

![image](https://cloud.githubusercontent.com/assets/2996260/11457248/16bc83b4-96a4-11e5-817d-bfd2240b4906.png)

It is not intended for use with Windows or contains an error.
Try reinstalling the program from the original installation media or contact the administrator or the software supplier.
State error 0xc000012f

**Comment by ValdikSS** [comment]
Make sure you downloaded dll and not html file. Try to open it in notepad.
Press "View Raw" to download.

**Comment by byman64** [comment]
You are right! it's the html page...let me download the right file..and then I will revert if it works...

**Comment by byman64** [comment]
IT WORKS FINE!

Great Job!

It would be nice as option on OpenVPN.

thanks again

**Comment by ValdikSS** [comment]
It would be included in OpenVPN 2.3.9.
