### ISSUE TITLE
Viscosity support

### ISSUE THREAD

**Issue by ahrenstein** [ValdikSS/openvpn-fix-dns-leak-plugin#7]
Using either OpenVPN or the latest Viscosity for Windows, I get the following error:

```
Dec 07 1:58:16 PM: State changed to Connecting
Dec 07 1:58:16 PM: Viscosity Windows 1.5.10 (1385)
Dec 07 1:58:16 PM: Running on Microsoft Windows 10 Enterprise
Dec 07 1:58:16 PM: Bringing up interface...
Dec 07 1:58:16 PM: Checking reachability status of connection...
Dec 07 1:58:17 PM: Connection is reachable. Starting connection attempt.
Dec 07 1:58:17 PM: PLUGIN_INIT: could not load plugin DLL: C:\Program Files\Viscosity\vpn-dns-fix-64.dll: %1 is not a valid Win32 application.   (errno=193)
Dec 07 1:58:17 PM: Exiting due to fatal error

The OpenVPN subsystem could not be started. Please check the following:
- Check for any error messages above this notification.
- Ensure ViscosityService is running.
- Make sure the configuration is valid if this is a Custom Gateway.

Dec 07 1:58:23 PM: State changed to Disconnected
```

This works with the 32-bit DLL but I'm running a 64-bit system so that DLL doesn't do anything.

**Comment by ValdikSS** [comment]
You probably using 32 bit OpenVPN. Try the older version of 32 bit dll:
https://github.com/ValdikSS/openvpn-fix-dns-leak-plugin/blob/a968d14ef92a2db5500e8f4dbd978f3dd06649db/fix-dns-leak-32.dll

**Comment by ahrenstein** [comment]
Will that matter if I'm using a 64-bit operating system?
Thanks

**Comment by ValdikSS** [comment]
You can use 32 bit or 64 bit OpenVPN on a 32 bit system but the latest 32 bit DNS Leak fix plugin has an issue when running on a 64 bit system. Try the link I gave you, it should work fine.

**Comment by ahrenstein** [comment]
Hmmm it's still resolving the external versions of the domain.
Does this project contain the source code for the DLLs?

**Comment by ValdikSS** [comment]
The leak happens? Do you have the information on what OpenVPN version does Viscosity use?

**Comment by ahrenstein** [comment]
It seems to be 2.3.8. I'll send a rar of the Viscosity folder to your e-mail address.

**Comment by ValdikSS** [comment]
I see. Viscosity uses it's own modified OpenVPN client and it's own modified TAP adapter. I'll update the plugin in some minutes and let you know.

**Comment by ahrenstein** [comment]
Awesome! Thanks! I'll test it out as soon as it's available.

**Comment by ValdikSS** [comment]
Please test the most recent version:
https://github.com/ValdikSS/openvpn-fix-dns-leak-plugin/blob/master/fix-dns-leak-32.dll

**Comment by ahrenstein** [comment]
That definitely blocks local DNS but for some odd reason remote DNS is not working. How odd. The same config works for Viscosity on OS X. I'll have to investigate that.

Thanks again.

**Comment by ValdikSS** [comment]
This could be because the plugin didn't find proper interface to allow DNS requests from. Can you please run Viscosity OpenVPN binary directly from the administrator console to see plugin's output and post it here please?

**Comment by ValdikSS** [comment]
Also, if you're using nslookup to test DNS please always write remote DNS server as an argument since nslookup doesn't use system lookup mechanism and tries to use non-vpn servers first.

nslookup google.com 192.168.100.1

**Comment by ahrenstein** [comment]
It looks like the VPN interface is being assigned the same DNS server as the local interface.

**Comment by ValdikSS** [comment]
You can try to force set it to 8.8.8.8 in Viscosity settings.

**Comment by ahrenstein** [comment]
Got it! Thanks
