### ISSUE TITLE
Webpages fail to load while plugin it enabled

### ISSUE THREAD

**Issue by Retrograde-Z** [ValdikSS/openvpn-fix-dns-leak-plugin#8]
I may be doing something stupid but after putting the plugin in my bin folder and adding plugin fix-dns-leak-64.dll to my .ovpn file, websites fail to load.  I get a DNS probe error and commenting the line out starts it working again. Any advice so I can hopefully stop my leaking DNS problem?

**Comment by ValdikSS** [comment]
You need to have DNS inside the tunnel which is configured statically on TAP interface or pushed from server with
`dhcp-option DNS`

**Comment by ValdikSS** [comment]
Please try OpenVPN 2.3.9 with `--block-outside-dns` and without this plugin.

**Comment by ValdikSS** [comment]
@Retrograde-Z did you try it?

**Comment by Retrograde-Z** [comment]
Hi ValdikSS,

I installed OpenVPN version 2.3.10 and put in openDNS entries for the dhcp-option DNS you mentioned back on Dec 18 and that seems to have fixed it. I have your plugin commented out in my config as I'm guessing it is no longer needed? Still leaking WebRTC in Chrome (known issue it looks like) but was able to stop it in Firefox by changing this option in about:config from true to false: media.peerconnection.enabled;false

Thanks for your help!
